## Multivariate Analysis 
```{r load_preprocess}
load("../data/raw/ames_train.Rdata")
train <- preprocess(ames_train, "train")
load("../data/raw/ames_test.Rdata")
test <- preprocess(ames_test, "test")
target <- 'price.log'
```

```{r pri}
pri <- importance(df, target)
topTerms <- pri %>% filter(aR2 > .25)
```

```{r interactions}
int <- interactions(df, target)
topInteractions <- int$effects %>% filter(aR2 > .71 & pValue < 0.05) %>% arrange(-aR2)

```

```{r model_gamma, cache=TRUE}
# Create formula
inter <- paste(sapply(seq(1:nrow(topInteractions)), function(i) {
  paste(topInteractions$Var1[i], topInteractions$Var2[i], sep = "*")
}), collapse = "+")
main <- paste(topTerms$term, collapse = "+")
combined <- paste(main, inter, sep = "+")
gFmla <- as.formula(paste(target, combined, sep = "~"))
```

```{r g_models_bma, cache=TRUE}
gBMA <- bas.lm(gFmla,  data=train, prior= 'ZS-null', modelprior=uniform(), initprobs="eplogp", method = "MCMC") 

# BMA Models
gammaHPM <- predict(gBMA, estimator = "HPM", newdata = test)
gammaBPM <- predict(gBMA, estimator = "BPM", newdata = test)
gammaBMA <- predict(gBMA, estimator = "BMA", newdata = test)
```

```{r g_models_step}
gamma <- lm(gFmla, data = train)
gammaStep <- stepAIC(gamma, direction = 'both', trace = FALSE)
gammaStepPred <- predict(gammaStep, newdata = test)


```


```{r eval_gamma}
# Train model and assess.
y <- exp(test$price.log)

#HPM 
yHat <- summary(gammaHPM$fit)
yHat <- exp(yHat)
g_RMSE_HPM <- sqrt(mean((y - yHat)^2))

# BPM
yHat <- gammaBPM$fit
yHat <- exp(yHat)
g_RMSE_BPM <- sqrt(mean((y - yHat)^2))

# BMA
yHat <- gammaBMA$fit
yHat <- exp(yHat)
g_RMSE_BPM <- sqrt(mean((y - yHat)^2))

# Step
# BPM
yHat <- summary(gammaStepPred)
yHat <- exp(yHat)
g_RMSE_Step <- sqrt(mean((y - yHat)^2))
```