---
title: "House Price Prediction with Bayesian Model Averaging"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(knitr.table.format = "html")
options(max.print=100, scipen=999, width = 800)
knitr::opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               eval = TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75, fig.height = 8)
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
```

```{r libraries}
library(analyzR)
library(broom)
library(corrplot)
library(data.table)
library(dplyr)
library(e1071)
library(extrafont)
library(ggplot2)
library(gridExtra)
library(Hmisc)
library(kfigr)
library(kableExtra)
library(psych)
library(stats)
library(xtable)
```
```{r functions}
source("../R/preprocess.R")
source("../R/reformat.R")
source("../R/convertOrdinals.R")
source("../R/univariate.R")
source("../R/visual.R")
```

```{r eda, child = 'eda2.rmd'}
```

